version: '3.9'

services:
  frontend:
    image: chs_frontend:latest
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - NEXT_PUBLIC_API_URL=https://chs.noahnielsen.dk
    depends_on:
      - backend

  backend:
    image: chs_backend:latest
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_URLS=http://+:5004
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Server=db,1433;Database=ChsB;User Id=sa;Password=yourStrong(!)Password;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1444:1433"
    healthcheck:
      test: [ "CMD-SHELL", "sqlcmd -S localhost -U sa -P yourStrong(!)Password -Q \"SELECT 1\"" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mssql_data:
