version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003" 
    environment:
      - ASPNETCORE_URLS=http://+:3003 
      - ASPNETCORE_ENVIRONMENT=Production
      - NODE_ENV=production
      - PORT = 3003
      - NEXT_PUBLIC_API_URL=https://chs.noahnielsen.dk 
      - CONNECTION_STRING=Server=db,1444;Database=CHSDB;User Id=sa;Password=yourStrong(!)Password;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1444:1433"

volumes:
  mssql_data:
